name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: SPM tests
      run: swift test
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:5.5-focal'
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: swift test
